services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    image: app:latest
    container_name: bit_integration_app
    volumes:
      - ./app:/var/www/app
    restart: always
    networks:
      - bit_integration_network
    environment:
      - X_SERVER_TYPE=app

  admin:
    build:
      context: .
      dockerfile: ./.docker/admin/Dockerfile
    image: admin:latest
    container_name: bit_integration_admin
    volumes:
      - ./admin:/var/www/admin
    restart: always
    networks:
      - bit_integration_network
    environment:
      - X_SERVER_TYPE=admin

  web:
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    image: web:latest
    container_name: bit_integration_web
    stdin_open: true
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    # env_file:
    #   - ./web/.env
    networks:
      - bit_integration_network
    environment:
      - X_SERVER_TYPE=web

  worker:
    build:
      context: .
      dockerfile: ./.docker/worker/Dockerfile
    image: worker:latest
    container_name: bit_integration_worker
    command: /usr/bin/supervisord -c /etc/supervisord.conf
    volumes:
      - ./app:/var/www/app
      - ./.data/logs/worker:/var/log
      - ./.docker/worker/worker.conf:/etc/supervisor/conf.d/worker.conf
    networks:
      - bit_integration_network
    environment:
      - X_SERVER_TYPE=worker

volumes:
  pgdata:
  redis:
    driver: local

networks:
  bit_integration_network:
    driver: bridge
