name: Docker Service Update

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Enter the service name to update (e.g., app, admin,worker)"
        required: true
        default: "app"

jobs:
  build-and-deploy:
    name: Build and Deploy Service
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      # Build Docker Image for the specified service
      - name: Build Docker Image
        run: |
          SERVICE=${{ github.event.inputs.service }}
          echo "Building Docker image for service: $SERVICE"
          docker-compose -f docker-compose-build.yml build $SERVICE

      # Tag and Push Docker Image to Docker Hub
      - name: Tag and Push Docker Image
        run: |
          SERVICE=${{ github.event.inputs.service }}
          IMAGE_NAME="${DOCKER_HUB_USERNAME}/${SERVICE}:latest"
          echo "Tagging image as $IMAGE_NAME"
          docker tag $SERVICE $IMAGE_NAME
          echo "Pushing image to Docker Hub"
          docker push $IMAGE_NAME

  # Deploy Updated Image to Server
  Continuous-Deployment:
    needs: build-and-deploy
    runs-on: [self-hosted] # Use self-hosted runner
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3

      - name: Deploy the application
        run: |
          SERVICE=${{ github.event.inputs.service }}
          echo "Deploying service: $SERVICE"

          # Change directory to the application folder
          cd ${{ secrets.AWS_DIRECTORY }}

          # Execute the deployment script with the service name
          ./update-service-new-images.sh $SERVICE
